env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  camelcase: 
    - error
  prefer-const:
    - warn
